# This file was generated by GoReleaser. DO NOT EDIT.
cask "prusactl" do
  version "0.1.3"

  on_macos do
    sha256 "ed81cad48e0638d4357a6628347edf4254c0088be04ad910576d10976c7a896f"
    url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "63c85195da16335d69ce6080daca4916ebdb32d560dda2e0f3ed51a825fdb8ae"
      url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "02a03ac9a607eeee5da51306c1ff9548ab6ce5db45f58a068f2cc8d269fcc67a"
      url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prusactl"
  desc "Run a Prusa 3D printer from the terminal or an AI agent (CLI + MCP server)"
  homepage "https://github.com/trevin-lee/prusactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prusactl"
  bash_completion "completions/prusactl.bash"
  fish_completion "completions/prusactl.fish"
  zsh_completion "completions/_prusactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prusactl"]
    end
  end

  # No zap stanza required
end
