# This file was generated by GoReleaser. DO NOT EDIT.
cask "prusactl" do
  version "0.1.1"

  on_macos do
    sha256 "6b704270f08eca81d9c31c7542965fc7205cfb9e0be64034f3572235f14f4e3b"
    url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "38242b5086493117c02751b3d27365cdbd966e071e970d4153f345c8fac8a76f"
      url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4e5f855f8dfff3bbf93a92c51718405a01d60d6aabe02a51dc992724d46dec9"
      url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prusactl"
  desc "Run a Prusa 3D printer from the terminal or an AI agent (CLI + MCP server)"
  homepage "https://github.com/trevin-lee/prusactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prusactl"
  bash_completion "completions/prusactl.bash"
  fish_completion "completions/prusactl.fish"
  zsh_completion "completions/_prusactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prusactl"]
    end
  end

  # No zap stanza required
end
