# This file was generated by GoReleaser. DO NOT EDIT.
cask "prusactl" do
  version "0.1.0"

  on_macos do
    sha256 "41007466f12ee5a97f8512fa6651b78eda69a5d3c4068bf848e7233428607313"
    url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "5102b57f785f760b4f70ac5e1451056b34c1fe18b6598e424099bef23e7fe951"
      url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fc8d864894c8af2546e6aebc3930a9cbe0ec952bae93c2764ee0193068c0bcc1"
      url "https://github.com/trevin-lee/prusactl/releases/download/v#{version}/prusactl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prusactl"
  desc "Run a Prusa 3D printer from the terminal or an AI agent (CLI + MCP server)"
  homepage "https://github.com/trevin-lee/prusactl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prusactl"
  bash_completion "completions/prusactl.bash"
  fish_completion "completions/prusactl.fish"
  zsh_completion "completions/_prusactl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prusactl"]
    end
  end

  # No zap stanza required
end
