# Generated by packaging/homebrew/formula.mjs in the ide-design repository. Do not edit here.
class IdeDesign < Formula
  desc "Parametric graphic design: token-only React artifacts checked like code"
  homepage "https://github.com/trevin-lee/ide-design"
  url "https://github.com/trevin-lee/ide-design/releases/download/v0.5.0/ide-design-0.5.0.tgz"
  sha256 "f91885f54f05dda66bcd85337beb32d8f99079d92f397e59e30db7686060e158"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    # Always run on Homebrew's Node, whichever version manager is first on PATH.
    (bin/"ided").write_env_script libexec/"bin/ided", PATH: "#{formula_opt_bin("node")}:$PATH"
  end

  def caveats
    <<~EOS
      Connect ided to Claude Code and Codex (skills and MCP server):
        ided setup

      PDF and PNG export use a pinned Chromium, downloaded on the first
      export (about 100 MB), or now with:
        ided browser install

      Before uninstalling, remove the skills and MCP server from your agents:
        ided setup --remove
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ided --version")
    system bin/"ided", "init", "--here", "--name", "Brew Test"
    # The layout check measures frames in a browser, which the test sandbox cannot download.
    assert_match "Clean", shell_output("#{bin}/ided check --no-layout")
    system bin/"ided", "export", "brand", "--out", "out"
    assert_path_exists testpath/"out/brew-test-brand-kit/logos/mark/mark-primary.svg"
  end
end
