# Generated by packaging/homebrew/formula.mjs in the ide-design repository. Do not edit here.
class IdeDesign < Formula
  desc "Parametric graphic design: token-only React artifacts checked like code"
  homepage "https://github.com/trevin-lee/ide-design"
  url "https://github.com/trevin-lee/ide-design/releases/download/v0.10.0/ide-design-0.10.0.tgz"
  sha256 "c14a21b1502699a64a15eddbb5e5a41ef5ce1a604ae710b85195a4090dba53be"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    # Always run on Homebrew's Node, whichever version manager is first on PATH.
    (bin/"ided").write_env_script libexec/"bin/ided", PATH: "#{formula_opt_bin("node")}:$PATH"
  end

  def caveats
    <<~EOS
      Connect ided to Claude Code and Codex (skills and MCP server):
        ided setup

      The layout check, screenshots and exports use a pinned Chromium,
      downloaded the first time one needs it (about 100 MB), or now with:
        ided browser install

      Before uninstalling, remove the skills and MCP server from your agents,
      and the downloaded Chromium:
        ided setup --remove
        ided browser remove
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ided --version")
    system bin/"ided", "init", "--here", "--name", "Brew Test"
    # The layout check measures frames in a browser, which the test sandbox cannot download.
    assert_match "Clean", shell_output("#{bin}/ided check --no-layout")
    system bin/"ided", "export", "brand", "--out", "out"
    assert_path_exists testpath/"out/brew-test-brand-kit/logos/mark/mark-primary.svg"
  end
end
