# Generated by packaging/homebrew/formula.mjs in the ided repository. Do not edit here.
class Ided < Formula
  desc "Parametric graphic design: token-only React artifacts checked like code"
  homepage "https://github.com/trevin-lee/ided"
  url "https://github.com/trevin-lee/ided/releases/download/v0.2.0/ided-0.2.0.tgz"
  sha256 "8aa3545dae92c512514540554abb967e3a5f66d18697412661e628a25ec18a6b"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    # Always run on Homebrew's Node, whichever version manager is first on PATH.
    (bin/"ided").write_env_script libexec/"bin/ided", PATH: "#{formula_opt_bin("node")}:$PATH"
  end

  def caveats
    <<~EOS
      Connect ided to Claude Code and Codex (skills and MCP server):
        ided setup

      PDF and PNG export use a pinned Chromium, downloaded on the first
      export (about 100 MB), or now with:
        ided browser install

      Before uninstalling, remove the skills and MCP server from your agents:
        ided setup --remove
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ided --version")
    system bin/"ided", "init", "--here", "--name", "Brew Test"
    assert_match "Clean", shell_output("#{bin}/ided check")
    system bin/"ided", "export", "brand", "--out", "out"
    assert_path_exists testpath/"out/brew-test-brand-kit/logos/mark/mark-primary.svg"
  end
end
