# Generated by packaging/homebrew/formula.mjs in the ided repository. Do not edit here.
class Ided < Formula
  desc "Parametric graphic design: token-only React artifacts checked like code"
  homepage "https://github.com/trevin-lee/ided"
  url "https://github.com/trevin-lee/ided/releases/download/v0.1.0/ided-0.1.0.tgz"
  sha256 "d6987c13ddde57d71d60c8dfd68f813a6da10ec476ad2f44b9dcd5a0017c7124"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    # Always run on Homebrew's Node, whichever version manager is first on PATH.
    (bin/"ided").write_env_script libexec/"bin/ided", PATH: "#{formula_opt_bin("node")}:$PATH"
  end

  def caveats
    <<~EOS
      Connect ided to Claude Code and Codex (skills and MCP server):
        ided setup

      PDF and PNG export use a pinned Chromium, downloaded on the first
      export (about 100 MB), or now with:
        ided browser install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ided --version")
    system bin/"ided", "init", "--here", "--name", "Brew Test"
    assert_match "Clean", shell_output("#{bin}/ided check")
    system bin/"ided", "export", "brand", "--out", "out"
    assert_path_exists testpath/"out/brew-test-brand-kit/logos/mark/mark-primary.svg"
  end
end
